### DISCUSSION TITLE
How do I include chapters?

### DISCUSSION THREAD

**Discussion by eduardz1** [tectonic-typesetting/tectonic#1235] [Q&A]
In LaTeX, it's common to subdivide your work in chapters in a "chapters" folder, however using the standard "\include" syntax doesn't seem to work, it's like it's including an empty chapter. My project is structured in this way:

```
.
├── latex
│   ├── guide
│   │   ├── chapters
│   │   │   └── a.tex
│   │   └── guide.tex
│   └── lib
│        ├── _postamble.tex
│        └── _preamble.tex
└── Tectonic.toml
```

It looks a bit complicated but it makes sense in the entire repository context. In the Tectonic.toml file I wrote:

```toml
[doc]
name = "eta-kappa-notes"
bundle = "https://data1.fullyjustified.net/tlextras-2022.0r0.tar"
extra_paths = ["latex"]

[[output]]
name = "guide"
type = "pdf"
shell_escape = true
inputs = ["lib/_preamble.tex", "guide/guide.tex", "lib/_postamble.tex"]
```

A minimal reproducible example would be `guide.tex` containing:

```latex
\title{Guide}

\maketitle
\tableofcontents

\include{chapters/a}
```

`a.tex` containing

```latex
\chapter{A}

a
```

`_preamble.tex` with

```latex
\documentclass[a4paper,12pt]{book}
\begin{document}
```

and `_postamble.tex` with

```latex
\end{document}
```

The resulting PDF does not contain the "A" chapter

![screenshot-2024-11-20-13-10-57](https://github.com/user-attachments/assets/6a6b91fa-fbe9-40b4-8e96-8aa69ccc4dfe)

I am using the latest version, compiled with cargo with

```bash
cargo install --git https://github.com/tectonic-typesetting/tectonic tectonic
```
