### ISSUE TITLE
V2 CLI: Include "tex" output type in Tectonic.toml

### ISSUE THREAD

**Issue by j0hax** [tectonic-typesetting/tectonic#1135]
Howdy! I am currently working with the V2 Interface.

Would it be possible to create a simple output option that produces one unified `.tex` file from index.tex, _preample.tex, etc. source files?

Implementing this would provide great flexibility for further processing; specifically, I would like pass my TeX source to Pandoc for conversion to EPUB.

Suggestion:

```toml
[doc]
name = 'my-document'
bundle = 'https://data1.fullyjustified.net/tlextras-2022.0r0.tar'

[[output]]
name = 'my-document'
type = 'pdf'

[[output]]
name = 'my-document-src'
type = 'tex'
```
