### ISSUE TITLE
`extra_paths` not working

### ISSUE THREAD

**Issue by VJMReichenbach** [tectonic-typesetting/tectonic#1243]
I want to specify an extra path in my `Tectonic.toml` file like described [here](https://tectonic-typesetting.github.io/book/latest/ref/tectonic-toml.html).
I have a `Tectonic.toml` file that looks like this:
```toml
[doc]
name = "thesis"
bundle = "https://data1.fullyjustified.net/tlextras-2022.0r0.tar"
extra_paths = ["~/tuda-ci/"]

[[output]]
name = "default"
type = "pdf"
```

I get this compilation error:
```
error: TOML parse error at line 4, column 1
  |
4 | extra_paths = ["~/tuda-ci/"]
  | ^^^^^^^^^^^
unknown field `extra_paths`, expected one of `name`, `bundle`, `metadata`
```

Am I using this wrong?
