### ISSUE TITLE
Tectonic.toml multiple outputs for the same document

### ISSUE THREAD

**Issue by jeffa5** [tectonic-typesetting/tectonic#745]
I assume there are already ideas for the multiple outputs section in `Tectonic.toml` but I thought it would be useful to maybe begin outlining some features or set some expectations.

One thing I'd like is the ability to specify the preamble, index, and postamble file locations in this config file. Then we'd be able to have one build manifest for different versions of a document, e.g. a draft version and a final one. If these aren't specified then they should just default to what they are now.

e.g.
```toml
[[output]]
name = "draft"
type = "pdf"
preamble = "_preamble_draft.tex"

[[output]]
name = "final"
type = "pdf"
preamble = "_preamble_final.tex"
```

I'm sure there are other situations when specifying these would come in useful. I'd be interested to hear any thoughts.
