### ISSUE TITLE
Tectonic doesn't work with self-created packages

### ISSUE THREAD

**Issue by carlosala** [tectonic-typesetting/tectonic#858]
I have a `main.tex` file, that has a `\usepackage{preamble_style}` package, twhich is defined in the same folder where main.tex is as a file `preamble_style.sty`.
You can see how is created in [this repo](https://github.com/victorballester7/complete-summaries)

**Comment by pkgw** [comment]
Thanks for linking the example — this certainly *should* work, and does most of the time. I'll have to check and see why it's not for you.

**Comment by carlosala** [comment]
Hi! Any news?

**Comment by pkgw** [comment]
Sorry, none yet. I've been busy with work and all of my Tectonic time has been going into finishing off a project that's been lingering for way too long I'll tag this as help wanted, and maybe someone else will be able to offer some advice?

**Comment by carlosala** [comment]
> Sorry, none yet. I've been busy with work and all of my Tectonic time has been going into finishing off a project that's been lingering for way too long I'll tag this as help wanted, and maybe someone else will be able to offer some advice?

Don't worry! Thanks for your time! By the moment I'm compiling with `latexmk` and `texlive` so it's not a problem for me.
Another time, thanks!

**Comment by sneakers-the-rat** [comment]
Just browsing through and saw this. 

Did a test build with `tectonic -X compile main.tex --keep-logs` and saw this in stderr

```
error: preamble_style.sty:19: Undefined control sequence
Writing `main.log` (7.05 KiB)
error: halted on potentially-recoverable error as specified
```

Which says that there is an undefined command within `preamble_style.sty`, rather than the file not being able to be loaded at all. Looking at the log...

```
(subfiles.sty
Package: subfiles 2020/02/14 v1.6 Multi-file projects (package)
 (import.sty
Package: import 2020/01/22  v 6.0
))
! Undefined control sequence.
l.19     \ifSubfilesClassLoaded

```

Seems like it grabbed an old version of `subfiles`, the `\ifSubfilesClassLoaded` was added to subfiles after the bundle was created (default is from 2020): https://github.com/gsalzer/subfiles/commit/e63fd195b40e8b102c1abf88c21bbb067b19e486

related to https://github.com/tectonic-typesetting/tectonic/issues/871 , https://github.com/tectonic-typesetting/tectonic/issues/841 -- seems like keeping the bundle updated is complicated from looking at those and some of the PRs where it was updated. Any help that can be given streamlining the process? Otherwise it seems like it should be possible to specify that CTAN should be used instead, maybe an entry in the `Tectonic.toml` file like

```toml
[doc]
name = 'title
bundle = 'https://data1.fullyjustified.net/tlextras-2020.0r0.tar'

[[output]]
name = 'title'
type = 'pdf'

[[source]]
name = 'CTAN'
url = 'https://mirrors.ctan.org/macros/latex/contrib/{package}.zip'

[[packages]]
[packages.subpages]
source = 'CTAN'
version = '^2.2'

[packages.otherpackage]
git = 'https://github.com/<user>/<package>/<package>.sty'
version '>=<hash>'
```
